version: '2'
services:
  db:
    image: mysql
    container_name: holidays-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./fixtures:/fixtures
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
    - 8085:8080

volumes:
 db_data:

