services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/mydb
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
    - 8085:8080

volumes:
  db_data: