INSERT INTO employees(first_name,
                      last_name,
                      phone_no,
                      email_address,
                      city,
                      zip_code,
                      post_city,
                      street,
                      house_number,
                      flat_number,
                      department,
                      holidays)
VALUES ('Adam', 'Superclass', '111222333', 'adam@company.com', 'Bylowo-Leśnictwo', '80-002', 'Kartuzy', '', '1', '',
        'ACTUARIAL_DEPARTMENT', 22.5),
       ('Jan', 'Maven', '222333444', 'jan@company.com', 'Gdynia', '80-001', 'Gdynia,Starowiejska', 'Nowa', '33', '',
        'SALES_DEPARTMENT', 44),
       ('Monika', 'Git', '444555666', 'monika@company.com', 'Gdańsk', '80-003', 'Gdańsk', 'Długa', '44/45', '3',
        'FINANCE_DEPARTMENT', 0),
       ('Karolina', 'Pullrequest', '999888777', 'karolina@company.com', 'Kościerzyna', '80-004', 'Kościerzyna',
        'Nowa', '5A', '', 'FINANCE_DEPARTMENT', 0.5);
