INSERT INTO employees(id,
                      firstName,
                      lastName,
                      phoneNo,
                      emailAddress,
                      city,
                      zipCode,
                      postCity,
                      street,
                      houseNumber,
                      flatNumber,
                      department,
                      holidays)
VALUES (0, 'Adam', 'Superclass', '111222333', 'adam@company.com', 'Bylowo-Leśnictwo', '80-002', 'Kartuzy', '', '5', '',
        'Departament Finansow', 22.5),
       (1, 'Jan', 'Maven', '222333444', 'jan@company.com', 'Gdynia', '80-001', 'Gdynia,Starowiejska', '5', '33',
        'Departament Aktuarialny', 44),
       (2, 'Monika', 'Git', '444555666', 'monika@company.com', 'Gdańsk', '80-003', 'Gdańsk', 'Długa', '44/45', '3',
        'Departament Sprzedazy', 0),
       (3, 'Karolina', 'Pullrequest', '999888777', 'karolina@company.com', 'Kościerzyna', '80-004', 'Kościerzyna',
        'Nowa', '5A', '', 'Departament Aktuarialny', 0.5);
